### ISSUE TITLE
Test coverage calculation

### ISSUE THREAD

**Issue by KillianH** [thinkinglabs/the-100-percent-code-coverage-fallacy#1]
Hello !

I have some questions on the test coverage combined with mutations.

Based on the readme : 

> Inside that organisation, having 30% test coverage was a big achievement, as most teams had no or very little test coverage. You can imagine the team was very proud. Until the day someone had the clever idea to run mutation tests against the code base. All of a sudden the test coverage dropped to 3%.

How the new coverage is calculated with the mutation tests ?

For example if pitest return 100% coverage on lines and 80%~ on mutations does that means that my coverage is 80% ?
Or I have to calculate the lines covered and exclude all remaining mutations to have the real coverage ?

Thanks you for your work 👍

**Comment by tdpauw** [comment]
Oh gosh, I completely missed your issue 🤦 

There is no real relation between mutation testing and code coverage metrics.
Code Coverage metrics give you information on how many lines are covered by tests, regardless of whether these tests are meaningful or not.
Mutation Tests will give you information on whether the tests are actually meaningful, i.e. detects if tests will catch faults.

So, we can't really translate the percentage of mutations killed into coverage.

**Comment by KillianH** [comment]
> Oh gosh, I completely missed your issue 🤦 
> 
> There is no real relation between mutation testing and code coverage metrics.
> Code Coverage metrics give you information on how many lines are covered by tests, regardless of whether these tests are meaningful or not.
> Mutation Tests will give you information on whether the tests are actually meaningful, i.e. detects if tests will catch faults.
> 
> So, we can't really translate the percentage of mutations killed into coverage.

Thanks 😁
